# Generated by Django 5.0.7 on 2024-08-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_optiona_alter_article_optionb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
    ]
